### ISSUE TITLE
Welding fighters

### ISSUE THREAD

**Issue by Batuganda** [a-random-lemurian/firlas-rules#4]
### Explanation of rule

First Last should definitely not be allowed to create an amalgamation of a ship by repeatedly welding or bolting fighters on to their ship. 77+ gun ports on one vessel is illegal

### Rule

First Last is not allowed to weld fighters on to their ship to "Create More Gun Ports"

**Comment by a-random-lemurian** [comment]
Great rule, but I still have to add a few more rules from 350 to roughly 410 before I add this. Please wait a little longer

**Comment by a-random-lemurian** [comment]
added
