### ISSUE TITLE
Archon Theft

### ISSUE THREAD

**Issue by mOctave** [a-random-lemurian/firlas-rules#6]
### Explanation of rule

Archons, being potentially sapient life forms, should not be treated like this:
<img width="538" alt="Screen Shot 2022-10-13 at 4 49 35 PM" src="https://user-images.githubusercontent.com/73318970/195731840-62fc5643-7340-4908-99ed-15afcf576d8f.png">
As you can see, they tend to go green when that happens to them, probably an indication of sickness brought on by dire mistreatment (or disgust for the Free Worlds).

### Rule

First Last is not allowed to kidnap an Archon for their personal use.

**Comment by a-random-lemurian** [comment]
Added by b6babfc
